[package]
name = "kryptopass-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
openssl = "0.10.64"
rand = "0.8.5"
toml = "0.8.12"
