[package]
name = "kryptopass-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.63"
toml = "0.8.19"
unicode-segmentation = "1.12.0"
