[properties]
version = "0.1.0"
lang = ["es"]
name = "Perfil Seguro Corporativo"
type = "password"

[requirements]
digits = {min = 2, max = 6}     # 2 a 6 dígitos
lowercase = {min = 2}           # mínimo 2 minúsculas
uppercase = {min = 2}           # mínimo 2 mayúsculas
symbols = {min = 1, max = 4}    # 1 a 4 símbolos
length = {min = 10, max = 64}   # 10 a 64 caracteres

[allowed]
include = ["U+30A2"]

[not_allowed]
exclude = ["U+1F600-U+1F64F"]

[es]
uppercase = ["U+0041-U+005A", "U+00D1"]
lowercase = ["U+0061-U+007A", "U+00F1"]
digits = ["U+0030-U+0039"]
symbols = ["U+0021-U+002F", "U+00A1"]

[rules]
pattern = "(uppercase){1}*"     # Debe empezar con una mayúscula y luego seguir con la generación normal
max-consecutive = 2             # máximo 2 caracteres consecutivos
min-entropy-bits = 24           # mínimo 24 bits de entropía

# min-length = 2 + 2 + 2 + 1 = 7
# max-length = 6 + 4 + (2 * x) = 12 + (2 * x)

# Pattern: 1 + x
