# Configuración de generación de contraseñas
[properties]
lang = ["es"] # Idiomas: Español       
name = "Perfil Seguro Corporativo" 
type = "password" # Tipo de generación: contraseña

[requirements]
digits = {min = 2, max = 6}      # Entre 2 y 6 dígitos
length = {min = 10, max = 64}    # Longitud entre 10 y 64 caracteres
lowercase = {min = 2, max = inf} # Al menos 2 letras minúsculas 
symbols = {min = 1, max = 4}     # Entre 1 y 4 símbolos
uppercase = {min = 2, max = inf} # Al menos 2 letras mayúsculas 

# Conjuntos de caracteres permitidos y excluidos
[allowed]
include = ["U+30A2"] # Katakana Letter A

[not_allowed]
exclude = ["U+00A8"] # Excluye: ¨

# Definición de conjuntos de caracteres para cada lenguaje 
[es]
uppercase = [
  "U+0041-U+005A",  # A-Z
  "U+00D1",         # Ñ
  "U+00C1",         # Á
  "U+00C9",         # É
  "U+00CD",         # Í
  "U+00D3",         # Ó
  "U+00DA",         # Ú
  "U+00DC"          # Ü
]

lowercase = [
  "U+0061-U+007A",  # a-z
  "U+00F1",         # ñ
  "U+00E1",         # á
  "U+00E9",         # é
  "U+00ED",         # í
  "U+00F3",         # ó
  "U+00FA",         # ú
  "U+00FC"          # ü
]

digits = [
  "U+0030-U+0039", # 0-9
]

symbols = [
  "U+0021-U+002F",  # !"#$%&'()*+,-./
  "U+003A-U+0040",  # :;<=>?@
  "U+005B-U+0060",  # [\]^_`
  "U+007B-U+007E",  # {|}~
  "U+00BF",         # ¿
  "U+00A1",         # ¡
  "U+00A8",         # ¨ (diéresis)
  "U+00AA",         # ª (emenino ordinal)
  "U+02DC",         # ˜ (virgulilla)
  "U+00B7",         # · (punto medio)
  "U+00B0"          # ° (signo de grado)
]

# Unicode Block “Emoticons”
emoticons = [
  "U+1F600-U+1F64F" # Emoticonos
]

# Reglas adicionales de seguridad
[rules]
max-consecutive = 2 # Máximo de caracteres consecutivos iguales
min-entropy-bits = 24 # Entropía mínima de 24 bits
